# Generated by Django 4.2.4 on 2023-08-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twerk_name', models.CharField(default='', max_length=13)),
                ('twerk_birth', models.DateField()),
                ('twerk_numb', models.CharField(default='', max_length=31)),
            ],
        ),
    ]
